# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tom/Documents/rayTracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tom/Documents/rayTracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tom/Documents/rayTracer/CMakeFiles /home/tom/Documents/rayTracer/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tom/Documents/rayTracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f src/CMakeFiles/common.dir/build.make src/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named rayTracer

# Build rule for target.
rayTracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rayTracer
.PHONY : rayTracer

# fast build rule for target.
rayTracer/fast:
	$(MAKE) -f src/CMakeFiles/rayTracer.dir/build.make src/CMakeFiles/rayTracer.dir/build
.PHONY : rayTracer/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f src/utils/CMakeFiles/utils.dir/build.make src/utils/CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named geometry

# Build rule for target.
geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 geometry
.PHONY : geometry

# fast build rule for target.
geometry/fast:
	$(MAKE) -f src/geometry/CMakeFiles/geometry.dir/build.make src/geometry/CMakeFiles/geometry.dir/build
.PHONY : geometry/fast

#=============================================================================
# Target rules for targets named tracers

# Build rule for target.
tracers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tracers
.PHONY : tracers

# fast build rule for target.
tracers/fast:
	$(MAKE) -f src/tracers/CMakeFiles/tracers.dir/build.make src/tracers/CMakeFiles/tracers.dir/build
.PHONY : tracers/fast

#=============================================================================
# Target rules for targets named lights

# Build rule for target.
lights: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lights
.PHONY : lights

# fast build rule for target.
lights/fast:
	$(MAKE) -f src/lights/CMakeFiles/lights.dir/build.make src/lights/CMakeFiles/lights.dir/build
.PHONY : lights/fast

#=============================================================================
# Target rules for targets named materials

# Build rule for target.
materials: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 materials
.PHONY : materials

# fast build rule for target.
materials/fast:
	$(MAKE) -f src/materials/CMakeFiles/materials.dir/build.make src/materials/CMakeFiles/materials.dir/build
.PHONY : materials/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... common"
	@echo "... rayTracer"
	@echo "... utils"
	@echo "... geometry"
	@echo "... tracers"
	@echo "... lights"
	@echo "... materials"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

